name: Build Windows EXE (Simple)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows-simple:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build JAR with Maven
      run: mvn clean package -q
      
    - name: Verify JAR creation
      run: |
        dir target\*.jar
        echo "JAR built successfully"
      shell: cmd
      
    - name: Download Launch4j
      run: |
        Invoke-WebRequest -Uri "https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-win32.zip/download" -OutFile "launch4j.zip"
        Expand-Archive -Path "launch4j.zip" -DestinationPath "."
      shell: powershell
      
    - name: Create Launch4j config
      run: |
        $config = @"
        <?xml version="1.0" encoding="UTF-8"?>
        <launch4jConfig>
          <dontWrapJar>false</dontWrapJar>
          <headerType>gui</headerType>
          <jar>target\Quoridor-1.0.2-shaded.jar</jar>
          <outfile>target\Quoridor.exe</outfile>
          <errTitle></errTitle>
          <cmdLine></cmdLine>
          <chdir>.</chdir>
          <priority>normal</priority>
          <downloadUrl>https://adoptium.net/temurin/releases/</downloadUrl>
          <supportUrl></supportUrl>
          <stayAlive>false</stayAlive>
          <restartOnCrash>false</restartOnCrash>
          <manifest></manifest>
          <icon></icon>
          <jre>
            <path></path>
            <bundledJre64Bit>false</bundledJre64Bit>
            <bundledJreAsFallback>false</bundledJreAsFallback>
            <minVersion>21</minVersion>
            <maxVersion></maxVersion>
            <jdkPreference>preferJre</jdkPreference>
            <runtimeBits>64/32</runtimeBits>
            <opt>-Dfile.encoding=UTF-8 -Dprism.forceGPU=true -Djavafx.animation.fullspeed=true -Xmx1024m</opt>
          </jre>
        </launch4jConfig>
        "@
        $config | Out-File -FilePath "launch4j-config.xml" -Encoding UTF8
      shell: powershell
      
    - name: Create EXE with Launch4j
      run: |
        .\launch4j\launch4j.exe launch4j-config.xml
      shell: cmd
      
    - name: Verify EXE creation
      run: |
        dir target\Quoridor.exe
        echo "EXE created successfully"
      shell: cmd
      
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: Quoridor-Windows-Simple
        path: target/Quoridor.exe
        
    - name: Create release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/Quoridor.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 